### ISSUE TITLE
how to compile this on linux?

### ISSUE THREAD

**Issue by fred0r** [bla0r/Fish-for-Hexchat#1]
how to compile this on linux?

**Comment by bla0r** [comment]
i updated the readme and the meson.build

**Comment by fred0r** [comment]
thank you, but still having problems compiling it:

```
meson builddir -Dlocal_install=true                    
The Meson build system
Version: 1.3.1
Source dir: /home/user/work/Fish-for-Hexchat
Build dir: /home/user/work/Fish-for-Hexchat/builddir
Build type: native build
meson.build:1:0: ERROR: Unknown options: "-std, local_install"
A full log can be found at /home/user/work/Fish-for-Hexchat/builddir/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

meson-log.txt

```
Build started at 2024-01-09T00:58:01.570221
Main binary: /usr/bin/python
Build Options: -Dlocal_install=true
Python system: Linux
The Meson build system
Version: 1.3.1
Source dir: /home/user/work/Fish-for-Hexchat
Build dir: /home/user/work/Fish-for-Hexchat/builddir
Build type: native build
meson.build:1:0: ERROR: Unknown options: "-std, local_install"
```

**Comment by bla0r** [comment]
should be fixed...

**Comment by fred0r** [comment]
looks promising, but still get a error:

```
meson builddir
The Meson build system
Version: 1.3.1
Source dir: /home/user/work/Fish-for-Hexchat
Build dir: /home/user/work/Fish-for-Hexchat/builddir
Build type: native build
Project name: blowfish
Project version: 1.0.0
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
C++ linker for the host machine: c++ ld.bfd 2.41.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.0
Run-time dependency hexchat-plugin found: YES 2.16.1
Run-time dependency gio-2.0 found: YES 2.78.3
Run-time dependency openssl found: YES 3.2.0
Checking for function "DH_set0_pqg" with dependency openssl: YES 
Checking for function "DH_get0_key" with dependency openssl: YES 
Checking for function "DH_set0_key" with dependency openssl: YES 
Configuring config.h using configuration

meson.build:56:15: ERROR: Unknown variable "hexchatplugindir".

A full log can be found at /home/user/work/Fish-for-Hexchat/builddir/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

meson-log.txt
```
Build started at 2024-01-10T21:18:27.858686
Main binary: /usr/bin/python
Build Options: 
Python system: Linux
The Meson build system
Version: 1.3.1
Source dir: /home/user/work/Fish-for-Hexchat
Build dir: /home/user/work/Fish-for-Hexchat/builddir
Build type: native build
Project name: blowfish
Project version: 1.0.0
-----------
Detecting compiler via: `c++ --version` -> 0
stdout:
c++ (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
-----------
Running command: c++ -E -dM -
-----
-----------
Detecting linker via: `c++ -Wl,--version` -> 0
stdout:
GNU ld (GNU Binutils) 2.41.0
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
-----------
stderr:
collect2-Version 13.2.1 20230801
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccMlV1Bw.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/Scrt1.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1 -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../.. --version -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/crtn.o
-----------
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
C++ linker for the host machine: c++ ld.bfd 2.41.0
-----------
Detecting linker via: `gcc-ar --version` -> 0
stdout:
GNU ar (GNU Binutils) 2.41.0
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
-----------
-----------
Detecting compiler via: `c++ --version` -> 0
stdout:
c++ (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
-----------
Running command: c++ -E -dM -
-----
-----------
Detecting linker via: `c++ -Wl,--version` -> 0
stdout:
GNU ld (GNU Binutils) 2.41.0
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
-----------
stderr:
collect2-Version 13.2.1 20230801
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/cclMC1aO.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/Scrt1.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1 -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../.. --version -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/crtn.o
-----------
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
C++ linker for the build machine: c++ ld.bfd 2.41.0
-----------
Detecting linker via: `gcc-ar --version` -> 0
stdout:
GNU ar (GNU Binutils) 2.41.0
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
-----------
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.0
Determining dependency 'hexchat-plugin' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --modversion hexchat-plugin` -> 0
stdout:
2.16.1
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --cflags hexchat-plugin` -> 0
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs hexchat-plugin` -> 0
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs hexchat-plugin` -> 0
Run-time dependency hexchat-plugin found: YES 2.16.1
Determining dependency 'gio-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --modversion gio-2.0` -> 0
stdout:
2.78.3
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --cflags gio-2.0` -> 0
stdout:
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -pthread
-----------
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs gio-2.0` -> 0
stdout:
-L/usr/lib -lgio-2.0 -lgobject-2.0 -lglib-2.0
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs gio-2.0` -> 0
stdout:
-lgio-2.0 -lgobject-2.0 -lglib-2.0
-----------
Running compile:
Working directory:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmp6edv59g9
Code:
 
        #include<stddef.h>
        #include<stdio.h>
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        }
-----------
Command line: `c++ /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmp6edv59g9/testfile.cpp -o /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmp6edv59g9/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive` -> 0
Program stdout:

8

Program stderr:


Running compile:
Working directory:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpblkt6oig
Code:
 
-----------
Command line: `c++ /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpblkt6oig/testfile.cpp -o /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpblkt6oig/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -fpermissive --print-search-dirs` -> 0
stdout:
install: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/
programs: =/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/lib/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../x86_64-pc-linux-gnu/13.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/:/lib/x86_64-pc-linux-gnu/13.2.1/:/lib/../lib/:/usr/lib/x86_64-pc-linux-gnu/13.2.1/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../:/lib/:/usr/lib/
-----------
Run-time dependency gio-2.0 found: YES 2.78.3
Determining dependency 'openssl' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --modversion openssl` -> 0
stdout:
3.2.0
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --cflags openssl` -> 0
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs openssl` -> 0
stdout:
-L/usr/lib -lssl -lcrypto
-----------
env[PKG_CONFIG_PATH]: 
env[PKG_CONFIG]: /usr/bin/pkg-config
-----------
Called: `/usr/bin/pkg-config --libs openssl` -> 0
stdout:
-lssl -lcrypto
-----------
Run-time dependency openssl found: YES 3.2.0
Running compile:
Working directory:  /tmp/tmpif5dr3od
Code:
 int i = static_cast<int>(0);
-----------
Command line: `c++ /tmp/tmpif5dr3od/testfile.cpp -o /tmp/tmpif5dr3od/output.obj -D_FILE_OFFSET_BITS=64 -c -std=c++14` -> 0
Compiler accepts -std=c++14: YES
Running compile:
Working directory:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpasrxe5r3
Code:
 
        #define DH_set0_pqg meson_disable_define_of_DH_set0_pqg
        
        #include <limits.h>
        #undef DH_set0_pqg
        
        #ifdef __cplusplus
        extern "C"
        #endif
        char DH_set0_pqg (void);
        
        #if defined __stub_DH_set0_pqg || defined __stub___DH_set0_pqg
        fail fail fail this function is not going to work
        #endif
        
        int main(void) {
          return DH_set0_pqg ();
        }
-----------
Command line: `c++ /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpasrxe5r3/testfile.cpp -o /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpasrxe5r3/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -std=c++14 -Wl,--start-group /usr/lib/libssl.so /usr/lib/libcrypto.so -Wl,--end-group` -> 0
Checking for function "DH_set0_pqg" with dependency openssl: YES 
Running compile:
Working directory:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpl2ph5td9
Code:
 
        #define DH_get0_key meson_disable_define_of_DH_get0_key
        
        #include <limits.h>
        #undef DH_get0_key
        
        #ifdef __cplusplus
        extern "C"
        #endif
        char DH_get0_key (void);
        
        #if defined __stub_DH_get0_key || defined __stub___DH_get0_key
        fail fail fail this function is not going to work
        #endif
        
        int main(void) {
          return DH_get0_key ();
        }
-----------
Command line: `c++ /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpl2ph5td9/testfile.cpp -o /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpl2ph5td9/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -std=c++14 -Wl,--start-group /usr/lib/libssl.so /usr/lib/libcrypto.so -Wl,--end-group` -> 0
Checking for function "DH_get0_key" with dependency openssl: YES 
Running compile:
Working directory:  /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpt0m5a_3x
Code:
 
        #define DH_set0_key meson_disable_define_of_DH_set0_key
        
        #include <limits.h>
        #undef DH_set0_key
        
        #ifdef __cplusplus
        extern "C"
        #endif
        char DH_set0_key (void);
        
        #if defined __stub_DH_set0_key || defined __stub___DH_set0_key
        fail fail fail this function is not going to work
        #endif
        
        int main(void) {
          return DH_set0_key ();
        }
-----------
Command line: `c++ /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpt0m5a_3x/testfile.cpp -o /home/user/work/Fish-for-Hexchat/builddir/meson-private/tmpt0m5a_3x/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -std=c++14 -Wl,--start-group /usr/lib/libssl.so /usr/lib/libcrypto.so -Wl,--end-group` -> 0
Checking for function "DH_set0_key" with dependency openssl: YES 
Configuring config.h using configuration

meson.build:56:15: ERROR: Unknown variable "hexchatplugindir".
```

**Comment by bla0r** [comment]
try again, removed hexchatplugindir

**Comment by fred0r** [comment]
now getting errors during compile.
just to be sure:
i assume, since i'm able to compile [otr](https://github.com/TingPing/hexchat-otr) w/o error, compiling this fish should generally work - correct?

meson builddir
```
The Meson build system
Version: 1.3.1
Source dir: /home/user/work/Fish-for-Hexchat
Build dir: /home/user/work/Fish-for-Hexchat/builddir
Build type: native build
Project name: blowfish
Project version: 1.0.0
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
C++ linker for the host machine: c++ ld.bfd 2.41.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.0
Run-time dependency hexchat-plugin found: YES 2.16.1
Run-time dependency gio-2.0 found: YES 2.78.3
Run-time dependency openssl found: YES 3.2.0
Checking for function "DH_set0_pqg" with dependency openssl: YES 
Checking for function "DH_get0_key" with dependency openssl: YES 
Checking for function "DH_set0_key" with dependency openssl: YES 
Configuring config.h using configuration
Build targets in project: 1

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated. 
```

ninja -C builddir install

```
ninja: Entering directory `builddir'
[1/9] Compiling C++ object blowfish.so.p/ircmessage.cpp.o
FAILED: blowfish.so.p/ircmessage.cpp.o 
c++ -Iblowfish.so.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -g -fPIC -pthread -MD -MQ blowfish.so.p/ircmessage.cpp.o -MF blowfish.so.p/ircmessage.cpp.o.d -o blowfish.so.p/ircmessage.cpp.o -c ../ircmessage.cpp
../ircmessage.cpp:1:10: schwerwiegender Fehler: IrcMessage.h: Datei oder Verzeichnis nicht gefunden
    1 | #include "IrcMessage.h"
      |          ^~~~~~~~~~~~~~
Kompilierung beendet.
[2/9] Compiling C++ object blowfish.so.p/blowfish.cpp.o
../blowfish.cpp: In Funktion »void blowfish_encrypt(const std::string&, std::string&, const std::string&)«:
../blowfish.cpp:28:19: Warnung: »void BF_set_key(BF_KEY*, int, const unsigned char*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   28 |         BF_set_key(&bf_key, key.size(), (unsigned char*)key.data());
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ../blowfish.cpp:3:
/usr/include/openssl/blowfish.h:50:28: Anmerkung: hier deklariert
   50 | OSSL_DEPRECATEDIN_3_0 void BF_set_key(BF_KEY *key, int len,
      |                            ^~~~~~~~~~
../blowfish.cpp:41:27: Warnung: »void BF_encrypt(unsigned int*, const BF_KEY*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   41 |                 BF_encrypt(&data.bf_long, &bf_key);
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:52:28: Anmerkung: hier deklariert
   52 | OSSL_DEPRECATEDIN_3_0 void BF_encrypt(BF_LONG *data, const BF_KEY *key);
      |                            ^~~~~~~~~~
../blowfish.cpp: In Funktion »int blowfish_decrypt(const std::string&, std::string&, const std::string&)«:
../blowfish.cpp:67:19: Warnung: »void BF_set_key(BF_KEY*, int, const unsigned char*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   67 |         BF_set_key(&bf_key, key.size(), (unsigned char*)key.data());
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:50:28: Anmerkung: hier deklariert
   50 | OSSL_DEPRECATEDIN_3_0 void BF_set_key(BF_KEY *key, int len,
      |                            ^~~~~~~~~~
../blowfish.cpp:82:27: Warnung: »void BF_decrypt(unsigned int*, const BF_KEY*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   82 |                 BF_decrypt(&data.bf_long, &bf_key);
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:53:28: Anmerkung: hier deklariert
   53 | OSSL_DEPRECATEDIN_3_0 void BF_decrypt(BF_LONG *data, const BF_KEY *key);
      |                            ^~~~~~~~~~
[3/9] Compiling C++ object blowfish.so.p/blowfish_cbc.cpp.o
FAILED: blowfish.so.p/blowfish_cbc.cpp.o 
c++ -Iblowfish.so.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -g -fPIC -pthread -MD -MQ blowfish.so.p/blowfish_cbc.cpp.o -MF blowfish.so.p/blowfish_cbc.cpp.o.d -o blowfish.so.p/blowfish_cbc.cpp.o -c ../blowfish_cbc.cpp
../blowfish_cbc.cpp: In Funktion »void blowfish_encrypt_cbc(const std::string&, std::string&, const std::string&)«:
../blowfish_cbc.cpp:70:9: Fehler: »memset« wurde in diesem Gültigkeitsbereich nicht definiert
   70 |         memset(l_bufIn, 0, l_inBufSize); // important for padding
      |         ^~~~~~
../blowfish_cbc.cpp:7:1: Anmerkung: »memset« ist im Header »<cstring>« definiert; haben Sie vergessen, »#include <cstring>« zu schreiben?
    6 | #include <mutex>
  +++ |+#include <cstring>
    7 | 
../blowfish_cbc.cpp:83:9: Fehler: »memcpy« wurde in diesem Gültigkeitsbereich nicht definiert
   83 |         memcpy(l_bufIn, l_realIv, 8);
      |         ^~~~~~
../blowfish_cbc.cpp:83:9: Anmerkung: »memcpy« ist im Header »<cstring>« definiert; haben Sie vergessen, »#include <cstring>« zu schreiben?
[4/9] Compiling C++ object blowfish.so.p/keymanagement.cpp.o
FAILED: blowfish.so.p/keymanagement.cpp.o 
c++ -Iblowfish.so.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -g -fPIC -pthread -MD -MQ blowfish.so.p/keymanagement.cpp.o -MF blowfish.so.p/keymanagement.cpp.o.d -o blowfish.so.p/keymanagement.cpp.o -c ../keymanagement.cpp
../keymanagement.cpp: In Elementfunktion »std::string KeyManagement::keystoreGetKey(const std::string&, const std::string&, FishMode&)«:
../keymanagement.cpp:135:32: Fehler: »find_if« ist kein Element von »std«; meinten Sie »find«?
  135 |                 auto it = std::find_if(keystore.begin(), keystore.end(),
      |                                ^~~~~~~
      |                                find
[6/9] Compiling C++ object blowfish.so.p/plugin_hexchat.cpp.o
FAILED: blowfish.so.p/plugin_hexchat.cpp.o 
c++ -Iblowfish.so.p -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -g -fPIC -pthread -MD -MQ blowfish.so.p/plugin_hexchat.cpp.o -MF blowfish.so.p/plugin_hexchat.cpp.o.d -o blowfish.so.p/plugin_hexchat.cpp.o -c ../plugin_hexchat.cpp
../plugin_hexchat.cpp: In Funktion »int handle_incoming(char**, char**, hexchat_event_attrs*, void*)«:
../plugin_hexchat.cpp:145:25: Fehler: »make_shared« ist kein Element von »std«
  145 |         auto msg = std::make_shared<IrcMessage>(raw_message);
      |                         ^~~~~~~~~~~
../plugin_hexchat.cpp:15:1: Anmerkung: »std::make_shared« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
   14 | #include "utils.h"
  +++ |+#include <memory>
   15 | 
../plugin_hexchat.cpp:145:47: Fehler: expected primary-expression before »>« token
  145 |         auto msg = std::make_shared<IrcMessage>(raw_message);
      |                                               ^
../plugin_hexchat.cpp: In Funktion »int handle_keyx_notice(char**, char**, void*)«:
../plugin_hexchat.cpp:355:25: Fehler: »make_shared« ist kein Element von »std«
  355 |         auto msg = std::make_shared<IrcMessage>(raw_message);
      |                         ^~~~~~~~~~~
../plugin_hexchat.cpp:355:25: Anmerkung: »std::make_shared« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
../plugin_hexchat.cpp:355:47: Fehler: expected primary-expression before »>« token
  355 |         auto msg = std::make_shared<IrcMessage>(raw_message);
      |                                               ^
../plugin_hexchat.cpp: In Funktion »int handle_crypt_topic(char**, char**, void*)«:
../plugin_hexchat.cpp:419:73: Warnung: Format »%s« erwartet Argumenttyp »char*«, aber Argument 3 hat Typ »std::string« {aka »std::__cxx11::basic_string<char>«} [-Wformat=]
  419 |                 hexchat_printf(ph, "/settopic+ error, no key found for %s", chan);
      |                                                                        ~^
      |                                                                         |
      |                                                                         char*
[7/9] Compiling C++ object blowfish.so.p/dh1080.cpp.o
../dh1080.cpp: In Funktion »std::string DH1080_SHA256(const char*, size_t)«:
../dh1080.cpp:47:20: Warnung: »int SHA256_Init(SHA256_CTX*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   47 |         SHA256_Init(&l_ctx);
      |         ~~~~~~~~~~~^~~~~~~~
In Datei, eingebunden von ../dh1080.cpp:5:
/usr/include/openssl/sha.h:73:27: Anmerkung: hier deklariert
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
../dh1080.cpp:48:22: Warnung: »int SHA256_Update(SHA256_CTX*, const void*, size_t)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   48 |         SHA256_Update(&l_ctx, a_data, a_len);
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/sha.h:74:27: Anmerkung: hier deklariert
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
../dh1080.cpp:49:21: Warnung: »int SHA256_Final(unsigned char*, SHA256_CTX*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   49 |         SHA256_Final((unsigned char*)&l_shaBuf, &l_ctx);
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/sha.h:76:27: Anmerkung: hier deklariert
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~
../dh1080.cpp: In Funktion »std::string DhKeyToStr(DH*, bool)«:
../dh1080.cpp:66:28: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   66 |         if (a_dh && DH_size(a_dh) < 10240)
      |                     ~~~~~~~^~~~~~
In Datei, eingebunden von ../dh1080.cpp:3:
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:68:28: Warnung: »void DH_get0_pqg(const DH*, const BIGNUM**, const BIGNUM**, const BIGNUM**)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   68 |                 DH_get0_pqg(a_dh, &p, &q, &g);
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:260:28: Anmerkung: hier deklariert
  260 | OSSL_DEPRECATEDIN_3_0 void DH_get0_pqg(const DH *dh, const BIGNUM **p,
      |                            ^~~~~~~~~~~
../dh1080.cpp:70:49: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   70 |                 const size_t l_bufSize = DH_size(a_dh);
      |                                          ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:74:66: Warnung: »const BIGNUM* DH_get0_priv_key(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   74 |                 const BIGNUM* key = (a_privKey ? DH_get0_priv_key(a_dh) : DH_get0_pub_key(a_dh));
      |                                                  ~~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:269:37: Anmerkung: hier deklariert
  269 | OSSL_DEPRECATEDIN_3_0 const BIGNUM *DH_get0_priv_key(const DH *dh);
      |                                     ^~~~~~~~~~~~~~~~
../dh1080.cpp:74:90: Warnung: »const BIGNUM* DH_get0_pub_key(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   74 |                 const BIGNUM* key = (a_privKey ? DH_get0_priv_key(a_dh) : DH_get0_pub_key(a_dh));
      |                                                                           ~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:270:37: Anmerkung: hier deklariert
  270 | OSSL_DEPRECATEDIN_3_0 const BIGNUM *DH_get0_pub_key(const DH *dh);
      |                                     ^~~~~~~~~~~~~~~
../dh1080.cpp: In Funktion »bool _DH1080_Init(DH**)«:
../dh1080.cpp:89:26: Warnung: »DH* DH_new()« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   89 |         DH* l_dh = DH_new();
      |                    ~~~~~~^~
/usr/include/openssl/dh.h:206:27: Anmerkung: hier deklariert
  206 | OSSL_DEPRECATEDIN_3_0 DH *DH_new(void);
      |                           ^~~~~~
../dh1080.cpp:105:44: Warnung: »int DH_set0_pqg(DH*, BIGNUM*, BIGNUM*, BIGNUM*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  105 |                                 DH_set0_pqg(l_dh, p, nullptr, g);
      |                                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:262:27: Anmerkung: hier deklariert
  262 | OSSL_DEPRECATEDIN_3_0 int DH_set0_pqg(DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g);
      |                           ^~~~~~~~~~~
../dh1080.cpp:113:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  113 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp: In Funktion »bool DH1080_Generate(std::string&, std::string&)«:
../dh1080.cpp:128:29: Warnung: »int DH_check(const DH*, int*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  128 |                 if (DH_check(l_dh, &l_check) == 1 && l_check == 0)
      |                     ~~~~~~~~^~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:227:27: Anmerkung: hier deklariert
  227 | OSSL_DEPRECATEDIN_3_0 int DH_check(const DH *dh, int *codes);
      |                           ^~~~~~~~
../dh1080.cpp:130:44: Warnung: »int DH_generate_key(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  130 |                         if (DH_generate_key(l_dh) == 1)
      |                             ~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:230:27: Anmerkung: hier deklariert
  230 | OSSL_DEPRECATEDIN_3_0 int DH_generate_key(DH *dh);
      |                           ^~~~~~~~~~~~~~~
../dh1080.cpp:137:40: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  137 |                                 DH_free(l_dh);
      |                                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp:143:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  143 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp: In Funktion »std::string DH1080_Compute(const std::string&, const std::string&)«:
../dh1080.cpp:165:36: Warnung: »int DH_set0_key(DH*, BIGNUM*, BIGNUM*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  165 |                         DH_set0_key(l_dh, nullptr, priv_key);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:265:27: Anmerkung: hier deklariert
  265 | OSSL_DEPRECATEDIN_3_0 int DH_set0_key(DH *dh, BIGNUM *pub_key, BIGNUM *priv_key);
      |                           ^~~~~~~~~~~
../dh1080.cpp:175:56: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  175 |                                 int l_bufSize = DH_size(l_dh);
      |                                                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:180:71: Warnung: »int DH_compute_key(unsigned char*, const BIGNUM*, DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  180 |                                         int l_keySize = DH_compute_key((unsigned char*)l_key, l_remotePubKey, l_dh);
      |                                                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:231:27: Anmerkung: hier deklariert
  231 | OSSL_DEPRECATEDIN_3_0 int DH_compute_key(unsigned char *key,
      |                           ^~~~~~~~~~~~~~
../dh1080.cpp:194:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  194 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
ninja: build stopped: subcommand failed.

```

**Comment by bla0r** [comment]
it works on windows for sure. Compiled with Visual Studio 2022. 
Maybe someone can take a look into it for linux.

I wrote my own plugin, because the hexchat plugin FiSHLiM is broken.

**Comment by fred0r** [comment]
https://github.com/bla0r/Fish-for-Hexchat/pull/2

ninja -C builddir

```
ninja: Entering directory `builddir'
[1/9] Compiling C++ object blowfish.so.p/blowfish.cpp.o
../blowfish.cpp: In Funktion »void blowfish_encrypt(const std::string&, std::string&, const std::string&)«:
../blowfish.cpp:29:19: Warnung: »void BF_set_key(BF_KEY*, int, const unsigned char*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   29 |         BF_set_key(&bf_key, key.size(), (unsigned char*)key.data());
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ../blowfish.cpp:3:
/usr/include/openssl/blowfish.h:50:28: Anmerkung: hier deklariert
   50 | OSSL_DEPRECATEDIN_3_0 void BF_set_key(BF_KEY *key, int len,
      |                            ^~~~~~~~~~
../blowfish.cpp:42:27: Warnung: »void BF_encrypt(unsigned int*, const BF_KEY*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   42 |                 BF_encrypt(&data.bf_long, &bf_key);
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:52:28: Anmerkung: hier deklariert
   52 | OSSL_DEPRECATEDIN_3_0 void BF_encrypt(BF_LONG *data, const BF_KEY *key);
      |                            ^~~~~~~~~~
../blowfish.cpp: In Funktion »int blowfish_decrypt(const std::string&, std::string&, const std::string&)«:
../blowfish.cpp:68:19: Warnung: »void BF_set_key(BF_KEY*, int, const unsigned char*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   68 |         BF_set_key(&bf_key, key.size(), (unsigned char*)key.data());
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:50:28: Anmerkung: hier deklariert
   50 | OSSL_DEPRECATEDIN_3_0 void BF_set_key(BF_KEY *key, int len,
      |                            ^~~~~~~~~~
../blowfish.cpp:83:27: Warnung: »void BF_decrypt(unsigned int*, const BF_KEY*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   83 |                 BF_decrypt(&data.bf_long, &bf_key);
      |                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/blowfish.h:53:28: Anmerkung: hier deklariert
   53 | OSSL_DEPRECATEDIN_3_0 void BF_decrypt(BF_LONG *data, const BF_KEY *key);
      |                            ^~~~~~~~~~
[4/9] Compiling C++ object blowfish.so.p/dh1080.cpp.o
../dh1080.cpp: In Funktion »std::string DH1080_SHA256(const char*, size_t)«:
../dh1080.cpp:47:20: Warnung: »int SHA256_Init(SHA256_CTX*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   47 |         SHA256_Init(&l_ctx);
      |         ~~~~~~~~~~~^~~~~~~~
In Datei, eingebunden von ../dh1080.cpp:5:
/usr/include/openssl/sha.h:73:27: Anmerkung: hier deklariert
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
../dh1080.cpp:48:22: Warnung: »int SHA256_Update(SHA256_CTX*, const void*, size_t)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   48 |         SHA256_Update(&l_ctx, a_data, a_len);
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/sha.h:74:27: Anmerkung: hier deklariert
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
../dh1080.cpp:49:21: Warnung: »int SHA256_Final(unsigned char*, SHA256_CTX*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   49 |         SHA256_Final((unsigned char*)&l_shaBuf, &l_ctx);
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/sha.h:76:27: Anmerkung: hier deklariert
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~
../dh1080.cpp: In Funktion »std::string DhKeyToStr(DH*, bool)«:
../dh1080.cpp:66:28: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   66 |         if (a_dh && DH_size(a_dh) < 10240)
      |                     ~~~~~~~^~~~~~
In Datei, eingebunden von ../dh1080.cpp:3:
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:68:28: Warnung: »void DH_get0_pqg(const DH*, const BIGNUM**, const BIGNUM**, const BIGNUM**)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   68 |                 DH_get0_pqg(a_dh, &p, &q, &g);
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:260:28: Anmerkung: hier deklariert
  260 | OSSL_DEPRECATEDIN_3_0 void DH_get0_pqg(const DH *dh, const BIGNUM **p,
      |                            ^~~~~~~~~~~
../dh1080.cpp:70:49: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   70 |                 const size_t l_bufSize = DH_size(a_dh);
      |                                          ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:74:66: Warnung: »const BIGNUM* DH_get0_priv_key(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   74 |                 const BIGNUM* key = (a_privKey ? DH_get0_priv_key(a_dh) : DH_get0_pub_key(a_dh));
      |                                                  ~~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:269:37: Anmerkung: hier deklariert
  269 | OSSL_DEPRECATEDIN_3_0 const BIGNUM *DH_get0_priv_key(const DH *dh);
      |                                     ^~~~~~~~~~~~~~~~
../dh1080.cpp:74:90: Warnung: »const BIGNUM* DH_get0_pub_key(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   74 |                 const BIGNUM* key = (a_privKey ? DH_get0_priv_key(a_dh) : DH_get0_pub_key(a_dh));
      |                                                                           ~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:270:37: Anmerkung: hier deklariert
  270 | OSSL_DEPRECATEDIN_3_0 const BIGNUM *DH_get0_pub_key(const DH *dh);
      |                                     ^~~~~~~~~~~~~~~
../dh1080.cpp: In Funktion »bool _DH1080_Init(DH**)«:
../dh1080.cpp:89:26: Warnung: »DH* DH_new()« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   89 |         DH* l_dh = DH_new();
      |                    ~~~~~~^~
/usr/include/openssl/dh.h:206:27: Anmerkung: hier deklariert
  206 | OSSL_DEPRECATEDIN_3_0 DH *DH_new(void);
      |                           ^~~~~~
../dh1080.cpp:105:44: Warnung: »int DH_set0_pqg(DH*, BIGNUM*, BIGNUM*, BIGNUM*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  105 |                                 DH_set0_pqg(l_dh, p, nullptr, g);
      |                                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:262:27: Anmerkung: hier deklariert
  262 | OSSL_DEPRECATEDIN_3_0 int DH_set0_pqg(DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g);
      |                           ^~~~~~~~~~~
../dh1080.cpp:113:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  113 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp: In Funktion »bool DH1080_Generate(std::string&, std::string&)«:
../dh1080.cpp:128:29: Warnung: »int DH_check(const DH*, int*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  128 |                 if (DH_check(l_dh, &l_check) == 1 && l_check == 0)
      |                     ~~~~~~~~^~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:227:27: Anmerkung: hier deklariert
  227 | OSSL_DEPRECATEDIN_3_0 int DH_check(const DH *dh, int *codes);
      |                           ^~~~~~~~
../dh1080.cpp:130:44: Warnung: »int DH_generate_key(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  130 |                         if (DH_generate_key(l_dh) == 1)
      |                             ~~~~~~~~~~~~~~~^~~~~~
/usr/include/openssl/dh.h:230:27: Anmerkung: hier deklariert
  230 | OSSL_DEPRECATEDIN_3_0 int DH_generate_key(DH *dh);
      |                           ^~~~~~~~~~~~~~~
../dh1080.cpp:137:40: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  137 |                                 DH_free(l_dh);
      |                                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp:143:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  143 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
../dh1080.cpp: In Funktion »std::string DH1080_Compute(const std::string&, const std::string&)«:
../dh1080.cpp:165:36: Warnung: »int DH_set0_key(DH*, BIGNUM*, BIGNUM*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  165 |                         DH_set0_key(l_dh, nullptr, priv_key);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:265:27: Anmerkung: hier deklariert
  265 | OSSL_DEPRECATEDIN_3_0 int DH_set0_key(DH *dh, BIGNUM *pub_key, BIGNUM *priv_key);
      |                           ^~~~~~~~~~~
../dh1080.cpp:175:56: Warnung: »int DH_size(const DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  175 |                                 int l_bufSize = DH_size(l_dh);
      |                                                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:210:27: Anmerkung: hier deklariert
  210 | OSSL_DEPRECATEDIN_3_0 int DH_size(const DH *dh);
      |                           ^~~~~~~
../dh1080.cpp:180:71: Warnung: »int DH_compute_key(unsigned char*, const BIGNUM*, DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  180 |                                         int l_keySize = DH_compute_key((unsigned char*)l_key, l_remotePubKey, l_dh);
      |                                                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/dh.h:231:27: Anmerkung: hier deklariert
  231 | OSSL_DEPRECATEDIN_3_0 int DH_compute_key(unsigned char *key,
      |                           ^~~~~~~~~~~~~~
../dh1080.cpp:194:24: Warnung: »void DH_free(DH*)« ist veraltet: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  194 |                 DH_free(l_dh);
      |                 ~~~~~~~^~~~~~
/usr/include/openssl/dh.h:207:28: Anmerkung: hier deklariert
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
[7/9] Compiling C++ object blowfish.so.p/plugin_hexchat.cpp.o
../plugin_hexchat.cpp: In Funktion »int handle_keyx_notice(char**, char**, void*)«:
../plugin_hexchat.cpp:399:67: Warnung: Format »%s« erwartet Argumenttyp »char*«, aber Argument 4 hat Typ »std::string« {aka »std::__cxx11::basic_string<char>«} [-Wformat=]
  399 |                 hexchat_printf(ph, "FiSH: Stored new key for %s (%s)", msg->getSender().c_str(), std::string(fish_modes[mode]));
      |                                                                  ~^                                   ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |                                   |
      |                                                                   char*                               std::string {aka std::__cxx11::basic_string<char>}
../plugin_hexchat.cpp: In Funktion »int handle_crypt_topic(char**, char**, void*)«:
../plugin_hexchat.cpp:421:73: Warnung: Format »%s« erwartet Argumenttyp »char*«, aber Argument 3 hat Typ »std::string« {aka »std::__cxx11::basic_string<char>«} [-Wformat=]
  421 |                 hexchat_printf(ph, "/settopic+ error, no key found for %s", chan);
      |                                                                        ~^
      |                                                                         |
      |                                                                         char*

```

**Comment by fred0r** [comment]
when loading the compiled plugin i get:

`Fehler beim Mappen des Shared Objects`
(Error when mapping the shared object)

**Comment by fred0r** [comment]
maybe i've been trolled, but some ppl in #hexchat said, that c++ plugins wont work on linux - only plugins written in c
